 export const  actionTypes = {
    FETCH_PRODUCTS_REQUEST : 'FETCH_PRODUCTS_REQUEST',
    FETCH_PRODUCTS_SUCCESS : 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE : 'FETCH_PRODUCTS_FAILURE',

    INCREASE_QUANTITY : 'INCREASE_QUANTITY',
    DECREASE_QUANTITY : 'DECREASE_QUANTITY',
    // GET_ALL_PRODUCT : 'GET_ALL_PRODUCT';
    GET_NUMBER_CART : 'GET_NUMBER_CART',
   ADD_CART : 'ADD_CART',
  DELETE_CART : 'DELETE_CART'
    
}

